/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Role_Administration;

import Model.Organization.RepositoryOrganization;
import Model.Organization.Organization;
import Model.Organization.Organization.OrganizationType;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaswa
 */
public class ManagePanel_Organization extends javax.swing.JPanel {
    
    private RepositoryOrganization od;
    private JPanel panel;

    /**
     * Creates new form ManagePanel_Account
     */
    public ManagePanel_Organization(JPanel panel, RepositoryOrganization od) {
        initComponents();
        this.panel = panel;
        this.od = od;

        fillRows();
        fillCmb();
    }
    
    private void fillRows() {
        DefaultTableModel m = (DefaultTableModel) tblOrg.getModel();

        m.setRowCount(0);

        for (Organization o : od.getOrganizations()) {
            Object[] r = new Object[2];
            r[0] = o.getOrgId();
            r[1] = o.getOrgName();

            m.addRow(r);
        }
    }

    private void fillCmb() {
        cmbBoxOrg.removeAllItems();
        for (OrganizationType t : Organization.OrganizationType.values()) {
            if (!OrganizationType.Admin.getValue().equals(t.getValue())) {
                cmbBoxOrg.addItem(t);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBack = new javax.swing.JButton();
        buttonCreateOrg = new javax.swing.JButton();
        scrollPane2 = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        labelHeader = new javax.swing.JLabel();
        labelOrg1 = new javax.swing.JLabel();
        cmbBoxOrg = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 51, 51));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        buttonBack.setBackground(new java.awt.Color(204, 204, 204));
        buttonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonBack.setText("<< Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonCreateOrg.setBackground(new java.awt.Color(204, 204, 204));
        buttonCreateOrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCreateOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create_account_cancer.png"))); // NOI18N
        buttonCreateOrg.setText("Add Organization");
        buttonCreateOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateOrgActionPerformed(evt);
            }
        });

        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane2.setViewportView(tblOrg);

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(153, 255, 255));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setText("Manage Organization");

        labelOrg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelOrg1.setForeground(new java.awt.Color(153, 255, 255));
        labelOrg1.setText("Organization Type:");

        cmbBoxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBoxOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCreateOrg)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(labelOrg1)
                .addGap(34, 34, 34)
                .addComponent(cmbBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader)
                .addGap(62, 62, 62)
                .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrg1)
                    .addComponent(cmbBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCreateOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        panel.remove(this);
        CardLayout crd = (CardLayout) panel.getLayout();
        crd.previous(panel); // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonCreateOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateOrgActionPerformed
       try {
        OrganizationType t = (OrganizationType) cmbBoxOrg.getSelectedItem();

        // Check if an organization type is selected
        if (t == null) {
            throw new IllegalArgumentException("Please select an Organization Type.");
        }

        // Add the organization to the organization directory
        od.addOrg(t);

        // Update the user interface (assuming fillRows() does that)
        fillRows();

        // Display a success message
        JOptionPane.showMessageDialog(this, "Organization created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Invalid Input", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Print the stack trace for debugging purposes
    }
    }//GEN-LAST:event_buttonCreateOrgActionPerformed

    private void cmbBoxOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCreateOrg;
    private javax.swing.JComboBox cmbBoxOrg;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelOrg1;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTable tblOrg;
    // End of variables declaration//GEN-END:variables
}
