/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminstrativeRole;

import Business.CustomerClass;
import Business.CustDir;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VAMSI VAS
 */
public class ManageCustJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustJPanel
     */
    private JPanel userProcessContainer;
    private CustDir customerDirectory;

    public ManageCustJPanel(JPanel userProcessContainer, CustDir customerDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerDirectory = customerDirectory;
        
        populateCustomerTable();
    }
    
    private void populateCustomerTable()
    {
        DefaultTableModel dtm= (DefaultTableModel) custJT.getModel();
        dtm.setRowCount(0);
        
        for(CustomerClass customer:customerDirectory.getCustomerDirectory())
        {
            Object row[]= new Object[2];
            row[0]=customer;
            row[1]=customer.getCustName();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCustJButton = new javax.swing.JButton();
        rmvCustJBtn = new javax.swing.JButton();
        viewCustJBtn = new javax.swing.JButton();
        rfrshJBtn = new javax.swing.JButton();
        JBtnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        custJT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        addCustJButton.setBackground(new java.awt.Color(255, 204, 204));
        addCustJButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addCustJButton.setForeground(new java.awt.Color(51, 51, 51));
        addCustJButton.setText("Add Customer");
        addCustJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustJButtonActionPerformed(evt);
            }
        });

        rmvCustJBtn.setBackground(new java.awt.Color(255, 204, 204));
        rmvCustJBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        rmvCustJBtn.setForeground(new java.awt.Color(51, 51, 51));
        rmvCustJBtn.setText("Remove");
        rmvCustJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvCustJBtnActionPerformed(evt);
            }
        });

        viewCustJBtn.setBackground(new java.awt.Color(255, 204, 204));
        viewCustJBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewCustJBtn.setForeground(new java.awt.Color(51, 51, 51));
        viewCustJBtn.setText("View Customer");
        viewCustJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustJBtnActionPerformed(evt);
            }
        });

        rfrshJBtn.setBackground(new java.awt.Color(255, 204, 204));
        rfrshJBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        rfrshJBtn.setForeground(new java.awt.Color(51, 51, 51));
        rfrshJBtn.setText("Refresh");
        rfrshJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfrshJBtnActionPerformed(evt);
            }
        });

        JBtnBack.setBackground(new java.awt.Color(255, 204, 204));
        JBtnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        JBtnBack.setForeground(new java.awt.Color(51, 51, 51));
        JBtnBack.setText("<<Back");
        JBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnBackActionPerformed(evt);
            }
        });

        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));

        custJT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Customer ID", "Customer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(custJT);

        jLabel1.setFont(new java.awt.Font("Telugu MN", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Customers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rfrshJBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(JBtnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(viewCustJBtn)
                                    .addComponent(addCustJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rmvCustJBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(rfrshJBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtnBack)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewCustJBtn)
                        .addGap(18, 18, 18)
                        .addComponent(addCustJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rmvCustJBtn)
                        .addGap(73, 73, 73))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCustJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustJButtonActionPerformed
        // TODO add your handling code here:
        AddCustJPanel acjp= new AddCustJPanel(userProcessContainer,customerDirectory);
        userProcessContainer.add("AddCustomerJPanel", acjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addCustJButtonActionPerformed

    private void rmvCustJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvCustJBtnActionPerformed
        // TODO add your handling code here:
       int selectedRow = custJT.getSelectedRow();
if (selectedRow < 0) {
    JOptionPane.showMessageDialog(this, "Please select a Customer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

int flag = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this customer?", "Warning", JOptionPane.YES_NO_OPTION);
if (flag == JOptionPane.YES_OPTION) {
    CustomerClass customer = (CustomerClass) custJT.getValueAt(selectedRow, 0);
    customerDirectory.removeCust(customer);
}

populateCustomerTable();

    }//GEN-LAST:event_rmvCustJBtnActionPerformed

    private void viewCustJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustJBtnActionPerformed
        // TODO add your handling code here:
      int selectedRow = custJT.getSelectedRow();
CustomerClass customer = (CustomerClass) custJT.getValueAt(selectedRow, 0);

if (selectedRow < 0) {
    JOptionPane.showMessageDialog(this, "Please select a Customer.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

ViewCustDetailsJPanel vcdjp = new ViewCustDetailsJPanel(userProcessContainer, customer);
userProcessContainer.add("ViewCustomerDetailsJPanel", vcdjp);
CardLayout layout = (CardLayout) userProcessContainer.getLayout();
layout.next(userProcessContainer);

        
    }//GEN-LAST:event_viewCustJBtnActionPerformed

    private void rfrshJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfrshJBtnActionPerformed
        // TODO add your handling code here:
       populateCustomerTable();               
    }//GEN-LAST:event_rfrshJBtnActionPerformed

    private void JBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_JBtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnBack;
    private javax.swing.JButton addCustJButton;
    private javax.swing.JTable custJT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rfrshJBtn;
    private javax.swing.JButton rmvCustJBtn;
    private javax.swing.JButton viewCustJBtn;
    // End of variables declaration//GEN-END:variables
}
