/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminstrativeRole;

import Business.CustomerClass;
import Business.Utils.MyPhnNumbVerifClass;
import Business.Utils.MyStrngVerifClass;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author goutam
 */
public class ViewCustDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerDetails
     */
    private JPanel userProcessContainer;
    private CustomerClass customer;

    public ViewCustDetailsJPanel(JPanel userProcessContainer, CustomerClass customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customer = customer;
        populateCustomerDetails();
        MyStrngVerifClass myStringVerifier= new MyStrngVerifClass();
        customerNJTF.setInputVerifier(myStringVerifier);
        addJTxtField.setInputVerifier(myStringVerifier);
        MyPhnNumbVerifClass myPhoneNumberVerifier= new MyPhnNumbVerifClass();
        phnNumbJTF.setInputVerifier(myPhoneNumberVerifier);
    }

    private void populateCustomerDetails() {
        custIDJTF.setText(String.valueOf(customer.getCustID()));
        customerNJTF.setText(customer.getCustName());
        addJTxtField.setText(customer.getAddr());
        phnNumbJTF.setText(customer.getPhnNumb());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL1 = new javax.swing.JLabel();
        custIDJTF = new javax.swing.JTextField();
        customerNJTF = new javax.swing.JTextField();
        phnNumbJTF = new javax.swing.JTextField();
        backJBtn = new javax.swing.JButton();
        saveJBtn = new javax.swing.JButton();
        updateJBtn = new javax.swing.JButton();
        jL4 = new javax.swing.JLabel();
        addJTxtField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        jL.setBackground(new java.awt.Color(255, 204, 204));
        jL.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jL.setText("Customer ID");

        jL2.setBackground(new java.awt.Color(255, 204, 204));
        jL2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jL2.setText("Name");

        jL3.setBackground(new java.awt.Color(255, 204, 204));
        jL3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jL3.setText("Address");

        jL1.setBackground(new java.awt.Color(255, 204, 204));
        jL1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jL1.setText("Phone Number");

        custIDJTF.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        custIDJTF.setEnabled(false);

        customerNJTF.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        customerNJTF.setEnabled(false);

        phnNumbJTF.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        phnNumbJTF.setEnabled(false);

        backJBtn.setBackground(new java.awt.Color(255, 204, 204));
        backJBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        saveJBtn.setBackground(new java.awt.Color(255, 204, 204));
        saveJBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        saveJBtn.setText("Save");
        saveJBtn.setEnabled(false);
        saveJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJBtnActionPerformed(evt);
            }
        });

        updateJBtn.setBackground(new java.awt.Color(255, 204, 204));
        updateJBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        updateJBtn.setText("Update");
        updateJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJBtnActionPerformed(evt);
            }
        });

        jL4.setFont(new java.awt.Font("Telugu MN", 1, 24)); // NOI18N
        jL4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL4.setText("View Customer Details");

        addJTxtField.setEditable(false);
        addJTxtField.setBackground(new java.awt.Color(255, 255, 255));
        addJTxtField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jL4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backJBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jL, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(jL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jL1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custIDJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phnNumbJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addJTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(customerNJTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                    .addComponent(saveJBtn))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(updateJBtn)
                                .addGap(104, 104, 104))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL)
                    .addComponent(custIDJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL2)
                    .addComponent(customerNJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL3)
                    .addComponent(addJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL1)
                    .addComponent(phnNumbJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateJBtn)
                    .addComponent(saveJBtn)
                    .addComponent(backJBtn))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJBtnActionPerformed
        // TODO add your handling code here:
        customerNJTF.setEnabled(true);
        addJTxtField.setEnabled(true);
        phnNumbJTF.setEnabled(true);

        updateJBtn.setEnabled(false);
        saveJBtn.setEnabled(true);
    }//GEN-LAST:event_updateJBtnActionPerformed

    private void saveJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJBtnActionPerformed
        // TODO add your handling code here:
        if(customerNJTF.getText().trim().length()==0 || addJTxtField.getText().length()==0 || phnNumbJTF.getText().trim().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Please enter all the values.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        customer.setCustName(customerNJTF.getText());
        customer.setAddr(addJTxtField.getText());
        customer.setPhnNumb(phnNumbJTF.getText());
        updateJBtn.setEnabled(true);
        saveJBtn.setEnabled(false);

        customerNJTF.setEnabled(false);
        addJTxtField.setEnabled(false);
        phnNumbJTF.setEnabled(false);
        JOptionPane.showMessageDialog(this,"Customer Updated!!", "Information", JOptionPane.INFORMATION_MESSAGE);
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_saveJBtnActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addJTxtField;
    private javax.swing.JButton backJBtn;
    private javax.swing.JTextField custIDJTF;
    private javax.swing.JTextField customerNJTF;
    private javax.swing.JLabel jL;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JTextField phnNumbJTF;
    private javax.swing.JButton saveJBtn;
    private javax.swing.JButton updateJBtn;
    // End of variables declaration//GEN-END:variables
}
