/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Student;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Course.Course;
import model.Course.CourseDirectory;
import model.Employer.Employer;
import model.Professor.Professor;
import model.Student.Student;
import model.Student.StudentDirectory;
import ui.Admin.EmployerJPanel;
import ui.CourseJPanel.CourseJPanel;
import ui.CourseJPanel.EnrollmentdetailsJPanel;

/**
 *
 * @author sushanthkumarreddyjanga
 */
public class StuViewDetails extends javax.swing.JPanel {
    JPanel work;
    StudentDirectory studentList;
    Student student;
    Course course;
    CourseDirectory courseList;
    Employer employer;
    
    

    /**
     * Creates new form StuViewDetails
     */
    

    

    public StuViewDetails(JPanel work, String userId, StudentDirectory studentList, Student student, Course course, CourseDirectory courseList, Employer employer) {
        initComponents();
        this.work=work;
        this.student=studentList.searchStudent(userId);
        this.studentList=studentList;
        this.course=course;
        this.courseList=courseList;
        this.employer=employer;
        
        showDetails(userId);
    }
    
        

    
    public void showDetails(String userId){
        if(student == null){
            JOptionPane.showMessageDialog(null, "Account does not exit","Information", JOptionPane.WARNING_MESSAGE);
        }
        else{
        txtNameStudent.setText(student.getName());
        txtnuidStudent.setText(student.getId());
        txtEmailStu.setText(student.getEmail());
        txtUNameStu.setText(student.getuName());
        txtPassStu.setText(student.getPassword());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNameStudent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnuidStudent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailStu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUNameStu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassStu = new javax.swing.JPasswordField();
        btnBackSV = new javax.swing.JButton();
        btnSaveSV = new javax.swing.JButton();
        btnUpdateSV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnCatalog = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        CRbtn = new javax.swing.JButton();

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Name:");

        txtNameStudent.setEditable(false);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("NUID:");

        txtnuidStudent.setEditable(false);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Email:");

        txtEmailStu.setEditable(false);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("UserName:");

        txtUNameStu.setEditable(false);

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Password:");

        txtPassStu.setEditable(false);

        btnBackSV.setText("Back");
        btnBackSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSVActionPerformed(evt);
            }
        });

        btnSaveSV.setText("Save");
        btnSaveSV.setEnabled(false);
        btnSaveSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSVActionPerformed(evt);
            }
        });

        btnUpdateSV.setText("Update");
        btnUpdateSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSVActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Details");

        jButton4.setText("Register Courses");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnCatalog.setText("Course Catalog");
        btnCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogActionPerformed(evt);
            }
        });

        jButton6.setText("Apply for Employer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Transcript Application");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        CRbtn.setText("Courses Registered");
        CRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackSV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateSV))
                    .addComponent(txtNameStudent)
                    .addComponent(txtnuidStudent)
                    .addComponent(txtEmailStu)
                    .addComponent(txtUNameStu)
                    .addComponent(txtPassStu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CRbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(btnBackSV)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnuidStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(CRbtn)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatalog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUNameStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPassStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveSV)
                    .addComponent(btnUpdateSV))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSVActionPerformed
        // TODO add your handling code here:
        btnSaveSV.setEnabled(true);
        txtNameStudent.setEditable(true);
        txtnuidStudent.setEditable(true);
        txtEmailStu.setEditable(true);
        txtUNameStu.setEditable(true);
        txtPassStu.setEditable(true);
        
        btnUpdateSV.setEnabled(false);
    }//GEN-LAST:event_btnUpdateSVActionPerformed

    private void btnBackSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSVActionPerformed
        // TODO add your handling code here:
        work.remove(this);
        CardLayout layout = (CardLayout) work.getLayout();
        layout.previous(work);
    }//GEN-LAST:event_btnBackSVActionPerformed

    private void btnSaveSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSVActionPerformed
        // TODO add your handling code here:
        String id = txtnuidStudent.getText();
        String name = txtNameStudent.getText();
        String email = txtEmailStu.getText();
        String uName= txtUNameStu.getText();
        String pwd = txtPassStu.getText();
        
        Student student = new Student(id, name, email,uName,pwd);
        studentList.addStudent(student);
        
        JOptionPane.showMessageDialog(this,"Registration Sucessfull");
        
        btnUpdateSV.setEnabled(true);
        btnSaveSV.setEnabled(false);
        txtNameStudent.setEditable(false);
        txtnuidStudent.setEditable(false);
        txtEmailStu.setEditable(false);
        txtUNameStu.setEditable(false);
        txtPassStu.setEditable(false);
    }//GEN-LAST:event_btnSaveSVActionPerformed

    private void btnCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogActionPerformed
        // TODO add your handling code here:
        CourseJPanel panel= new CourseJPanel(work, courseList, course);
        work.add("Course Panel", panel);
        CardLayout layout = (CardLayout) work.getLayout();
        layout.next(work);
        
    }//GEN-LAST:event_btnCatalogActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        EnrollmentdetailsJPanel sv = new EnrollmentdetailsJPanel(work, studentList, course, courseList, student);
        work.add("Panel", sv);
        CardLayout layout = (CardLayout) work.getLayout();
        layout.next(work);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRbtnActionPerformed
        // TODO add your handling code here:
        RCJPanel rc = new RCJPanel(work,student);
        work.add("RC",rc);
        CardLayout layout = (CardLayout) work.getLayout();
        layout.next(work);
    }//GEN-LAST:event_CRbtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Transcript tp = new Transcript(work, student);
        work.add("Tp",tp);
        CardLayout layout = (CardLayout) work.getLayout();
        layout.next(work);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        EmpApply tp = new EmpApply(work, student,employer);
        work.add("Tp",tp);
        CardLayout layout = (CardLayout) work.getLayout();
        layout.next(work);
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CRbtn;
    private javax.swing.JButton btnBackSV;
    private javax.swing.JButton btnCatalog;
    private javax.swing.JButton btnSaveSV;
    private javax.swing.JButton btnUpdateSV;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEmailStu;
    private javax.swing.JTextField txtNameStudent;
    private javax.swing.JPasswordField txtPassStu;
    private javax.swing.JTextField txtUNameStu;
    private javax.swing.JTextField txtnuidStudent;
    // End of variables declaration//GEN-END:variables
}
