/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminWorkArea;

import Model.AddressRepo;
import Model.DB4OUtil.DB4OUtil;
import Model.EcoSystem;
import Model.EnterPrise;
import Model.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VAMSI VAS
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */

      private JPanel upperConatiner;
      private EcoSystem eco;
      private AddressRepo addresslist;
    public ManageEnterpriseJPanel(JPanel userContainer,EcoSystem eco) {
        initComponents();
        this.upperConatiner = userContainer;
        this.eco = eco;
        addresslist =new AddressRepo();
        populateTable();
        populateComboBox();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networklabel = new javax.swing.JLabel();
        CmbNetkitem1 = new javax.swing.JComboBox();
        enterprisetypeLabel = new javax.swing.JLabel();
        CombEnterpriseitem2 = new javax.swing.JComboBox();
        nameLabel1 = new javax.swing.JLabel();
        textfield1 = new javax.swing.JTextField();
        ButtonBack = new javax.swing.JButton();
        ButtonSubmit = new javax.swing.JButton();
        MainLabel1 = new javax.swing.JLabel();
        jpanelscroll1 = new javax.swing.JScrollPane();
        nameTbl = new javax.swing.JTable();
        Remove = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        networklabel.setBackground(new java.awt.Color(204, 204, 204));
        networklabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        networklabel.setForeground(new java.awt.Color(153, 255, 255));
        networklabel.setText("Network:");

        CmbNetkitem1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterprisetypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enterprisetypeLabel.setForeground(new java.awt.Color(153, 255, 255));
        enterprisetypeLabel.setText("Enterprise Type:");

        CombEnterpriseitem2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(153, 255, 255));
        nameLabel1.setText("Name:");

        textfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield1ActionPerformed(evt);
            }
        });

        ButtonBack.setBackground(new java.awt.Color(204, 204, 204));
        ButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonBack.setText("<< Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonSubmit.setBackground(new java.awt.Color(0, 51, 153));
        ButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/submit_cancer.png"))); // NOI18N
        ButtonSubmit.setText("Submit");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        MainLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MainLabel1.setForeground(new java.awt.Color(153, 255, 255));
        MainLabel1.setText("Manage Enterprise");

        nameTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Network", "Type"
            }
        ));
        jpanelscroll1.setViewportView(nameTbl);

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(ButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(MainLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CmbNetkitem1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CombEnterpriseitem2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(150, 150, 150))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enterprisetypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(networklabel))
                                    .addGap(310, 310, 310))))))
                .addGap(213, 431, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(MainLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(networklabel)
                                    .addComponent(CmbNetkitem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enterprisetypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CombEnterpriseitem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(ButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield1ActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        upperConatiner.remove(this);
        Component[] cmpArray = upperConatiner.getComponents();
        Component component= cmpArray[cmpArray.length-1];
        SystemAdminWorkAreaJPanel sysAdmin = (SystemAdminWorkAreaJPanel) component;
        sysAdmin.populateTreewithData();
        CardLayout crd = (CardLayout) upperConatiner.getLayout();
        crd.previous(upperConatiner);// TODO add your handling code here:
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
      try{
        Network network = (Network) CmbNetkitem1.getSelectedItem();
        EnterPrise.EntType type = (EnterPrise.EntType) CombEnterpriseitem2.getSelectedItem();
        System.out.println(CombEnterpriseitem2.getSelectedItem());
        if (network == null || type == null) {
            throw new IllegalArgumentException("Invalid Input! Network and Enterprise type must be selected.");
        }
      
        String name = textfield1.getText();
         if (name.isEmpty()) {
            throw new IllegalArgumentException("Please enter the Enterprise name");
        }

        for (EnterPrise e: network.getEnterpriseRepo().getEnterpRepo()) {
            if (e.getOrgName().equals(name)) {
                 throw new IllegalStateException("Enterprise name already exists. Please select a different name.");
            }
        }
        EnterPrise enterprise = network.getEnterpriseRepo().AddEnterPrise(name, type);
          Model.Address adr = addresslist.insertAddress();
// adr address doesnot hace setEnterprise
        adr.setName(textfield1.getText());

        populateTable();  
        JOptionPane.showMessageDialog(this, "Enterprise '" + name + "' created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
        
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Invalid Input", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalStateException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Duplicate Name", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Print the stack trace for debugging purposes
    }
    }//GEN-LAST:event_ButtonSubmitActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
     int selectedRow = nameTbl.getSelectedRow();
    if (selectedRow >= 0) {
        String enterpriseName = (String) nameTbl.getModel().getValueAt(selectedRow, 0);
        String networkName = (String) nameTbl.getModel().getValueAt(selectedRow, 1);

        // Find the corresponding network
        Network selectedNetwork = null;
        for (Network ntw : eco.getNetworks()) {
            if (ntw.getNetwork_name().equals(networkName)) {
                selectedNetwork = ntw;
                break;
            }
        }

        if (selectedNetwork != null) {
            // Remove the enterprise from the network
            boolean removed = selectedNetwork.getEnterpriseRepo().removeEnterprise(enterpriseName);

            if (removed) {
                // Update the EcoSystem object in the db4o database
                DB4OUtil.getInstance().storeSystem(eco);

                // Update the table
                populateTable();

                JOptionPane.showMessageDialog(null, "Enterprise removed successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Enterprise not found");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Network not found");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select an enterprise to remove");
    }
    }//GEN-LAST:event_RemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JComboBox CmbNetkitem1;
    private javax.swing.JComboBox CombEnterpriseitem2;
    private javax.swing.JLabel MainLabel1;
    private javax.swing.JButton Remove;
    private javax.swing.JLabel enterprisetypeLabel;
    private javax.swing.JScrollPane jpanelscroll1;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTable nameTbl;
    private javax.swing.JLabel networklabel;
    private javax.swing.JTextField textfield1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       DefaultTableModel model = (DefaultTableModel) nameTbl.getModel();
       model.setRowCount(0);
       for(Network ntw : eco.getNetworks()){
       for(EnterPrise ent : ntw.getEnterpriseRepo().getEnterpRepo()){
        Object[] row = new Object[4];
        row[0] = ent.getOrgName();
        row[1] = ntw.getNetwork_name();
        row[2] = ent.getEnterprise_type().getValue();
        row[3] = ent.getZip();
        model.addRow(row);
    }
}
  
    }

    private void populateComboBox() {
    // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
   CmbNetkitem1.removeAllItems();
CombEnterpriseitem2.removeAllItems();
for(Network ntw : eco.getNetworks()){
    CmbNetkitem1.addItem(ntw);
}
for (EnterPrise.EntType type : EnterPrise.EntType.values()){
    CombEnterpriseitem2.addItem(type);
}


    }

}
