/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HealthCareEquipmentAdmin;

import Model.Account;
import Model.Employee;
import Model.EnterPrise;
import Model.Organization.Organization;
import Model.Role.Role;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaswa
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {




   private JPanel panel;
 private EnterPrise enter;
    /**
     * Creates new form ManageUserAccountJPanel
     */
    public ManageUserAccountJPanel(JPanel panel, EnterPrise enter) {
        initComponents();
this.panel = panel;
this.enter = enter;
populateOrganizationCMBbox();
        populateTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwdTextdfield = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        orgLabel1 = new javax.swing.JLabel();
        createuserBtn = new javax.swing.JButton();
        CmbboxOrga1 = new javax.swing.JComboBox();
        header_managelabel1 = new javax.swing.JLabel();
        empLabel1 = new javax.swing.JLabel();
        cmbboxemp2 = new javax.swing.JComboBox();
        roleLabel1 = new javax.swing.JLabel();
        cmbBoxrole3 = new javax.swing.JComboBox();
        usernameLabel1 = new javax.swing.JLabel();
        txtfield_username = new javax.swing.JTextField();
        passwordLabel1 = new javax.swing.JLabel();
        jpanelscroll1 = new javax.swing.JScrollPane();
        userTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 51, 51));
        setForeground(new java.awt.Color(153, 255, 255));

        pwdTextdfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTextdfieldActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        orgLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        orgLabel1.setForeground(new java.awt.Color(153, 255, 255));
        orgLabel1.setText("Organization  :");

        createuserBtn.setBackground(new java.awt.Color(204, 204, 204));
        createuserBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createuserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create_account_cancer.png"))); // NOI18N
        createuserBtn.setText("Create");
        createuserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createuserBtnActionPerformed(evt);
            }
        });

        CmbboxOrga1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbboxOrga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbboxOrga1ActionPerformed(evt);
            }
        });

        header_managelabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        header_managelabel1.setForeground(new java.awt.Color(153, 255, 255));
        header_managelabel1.setText("Manage User Account");

        empLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empLabel1.setForeground(new java.awt.Color(153, 255, 255));
        empLabel1.setText("Employee      :");

        cmbboxemp2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        roleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roleLabel1.setForeground(new java.awt.Color(153, 255, 255));
        roleLabel1.setText("Role             :");

        cmbBoxrole3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        usernameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(153, 255, 255));
        usernameLabel1.setText("User Name    :");

        passwordLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(153, 255, 255));
        passwordLabel1.setText("Password      :");

        userTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jpanelscroll1.setViewportView(userTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 222, Short.MAX_VALUE)
                .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header_managelabel1)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(orgLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(backBtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(empLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(roleLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(passwordLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pwdTextdfield, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(usernameLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbBoxrole3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbboxemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CmbboxOrga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createuserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(header_managelabel1)
                .addGap(40, 40, 40)
                .addComponent(jpanelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgLabel1)
                    .addComponent(CmbboxOrga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empLabel1)
                    .addComponent(cmbboxemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxrole3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(passwordLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(pwdTextdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createuserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pwdTextdfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTextdfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTextdfieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createuserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createuserBtnActionPerformed
        try {
        String userName = txtfield_username.getText();
        String password = pwdTextdfield.getText();
        Organization organization = (Organization) CmbboxOrga1.getSelectedItem();
        Employee employee = (Employee) cmbboxemp2.getSelectedItem();
        Role role = (Role) cmbBoxrole3.getSelectedItem();

        // Check if the username and password are empty
        if (userName.isEmpty() || password.isEmpty()) {
            throw new IllegalArgumentException("Please enter both username and password.");
        }

        // Check if an organization is selected
        if (organization == null) {
            throw new IllegalArgumentException("Please select an organization.");
        }

        // Check if an employee is selected
        if (employee == null) {
            throw new IllegalArgumentException("Please select an employee.");
        }

        // Check if a role is selected
        if (role == null) {
            throw new IllegalArgumentException("Please select a role.");
        }

        // Create the user account
        organization.getUserAccDir().createUserAccount(userName, password, employee, role);

        // Update the user interface (assuming populateTableData() does that)
        populateTableData();

        // Display a success message
        JOptionPane.showMessageDialog(this, "User account created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Invalid Input", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Print the stack trace for debugging purposes
    }
    }//GEN-LAST:event_createuserBtnActionPerformed

    private void CmbboxOrga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbboxOrga1ActionPerformed
        Organization organization = (Organization) CmbboxOrga1.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_CmbboxOrga1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbboxOrga1;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox cmbBoxrole3;
    private javax.swing.JComboBox cmbboxemp2;
    private javax.swing.JButton createuserBtn;
    private javax.swing.JLabel empLabel1;
    private javax.swing.JLabel header_managelabel1;
    private javax.swing.JScrollPane jpanelscroll1;
    private javax.swing.JLabel orgLabel1;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JTextField pwdTextdfield;
    private javax.swing.JLabel roleLabel1;
    private javax.swing.JTextField txtfield_username;
    private javax.swing.JTable userTbl;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables

    private void populateTableData() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel model = (DefaultTableModel) userTbl.getModel();
        model.setRowCount(0);
        for (Organization organization : enter.getOrgaDirectory().getOrganizations()){
            for (Account acc : organization.getUserAccDir().getAccountList()){
                Object row[] = new Object[2];
                row[0] = acc;
                row[1] = acc.getRole();
                ((DefaultTableModel)userTbl.getModel()).addRow(row);
                
            }
        }
    }

    private void populateEmployeeComboBox(Organization organization) {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         cmbboxemp2.removeAllItems();
        for (Employee employee : organization.getEmpRepo().getE_Repo()){
            cmbboxemp2.addItem(employee);
        }
    }

    private void populateRoleComboBox(Organization organization) {
       // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
 cmbBoxrole3.removeAllItems();
        for (Role role : organization.getRole()){
            cmbBoxrole3.addItem(role);
        
    }
    }

    private void populateOrganizationCMBbox() {
       // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    CmbboxOrga1.removeAllItems();
        for (Organization organization : enter.getOrgaDirectory().getOrganizations()){
            CmbboxOrga1.addItem(organization);
        }
}
}
