/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin.ProfDetails.StuDetails;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Employer.Employer;
import model.Employer.EmployerDirectory;

/**
 *
 * @author sushanthkumarreddyjanga
 */
public class EmployerDetails extends javax.swing.JPanel {
    JPanel work;
    Employer employer;
    EmployerDirectory employerList;

    /**
     * Creates new form EmployerDetails
     */
    public EmployerDetails() {
        initComponents();
    }

    public EmployerDetails(JPanel work, Employer result, EmployerDirectory employerList) {
        initComponents();
        this.work=work;
        this.employer= result;
        this.employerList=employerList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailP = new javax.swing.JTextField();
        txtSpeciality = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUNameP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassP = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnBackPD = new javax.swing.JButton();
        btnSavePD = new javax.swing.JButton();
        btnUpdatePD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Name:");

        txtName.setEditable(false);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Employer ID");

        txtEID.setEditable(false);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Email:");

        txtEmailP.setEditable(false);

        txtSpeciality.setEditable(false);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Work Area:");

        txtUNameP.setEditable(false);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("UserName:");

        txtPassP.setEditable(false);

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Password:");

        btnBackPD.setText("Back");
        btnBackPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackPDActionPerformed(evt);
            }
        });

        btnSavePD.setText("Save");
        btnSavePD.setEnabled(false);
        btnSavePD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePDActionPerformed(evt);
            }
        });

        btnUpdatePD.setText("Update");
        btnUpdatePD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employer Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUNameP)
                            .addComponent(txtSpeciality)
                            .addComponent(txtEmailP)
                            .addComponent(txtEID)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSavePD)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdatePD))
                            .addComponent(txtPassP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(337, 337, 337))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackPD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnBackPD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmailP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUNameP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPassP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSavePD)
                    .addComponent(btnUpdatePD))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackPDActionPerformed
        // TODO add your handling code here:
        work.remove(this);
        CardLayout layout = (CardLayout) work.getLayout();
        layout.previous(work);
    }//GEN-LAST:event_btnBackPDActionPerformed

    private void btnSavePDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePDActionPerformed
        // TODO add your handling code here:
        String id = txtEID.getText();
        String name = txtName.getText();
        String email = txtEmailP.getText();
        String speciality = txtSpeciality.getText();
        String uName= txtUNameP.getText();
        String pwd = txtPassP.getText();

        Employer emp = new Employer();
        employerList.addEmployer(emp);

        JOptionPane.showMessageDialog(this,"Registration Sucessfull");

        btnUpdatePD.setEnabled(true);
        btnSavePD.setEnabled(false);
        txtName.setEditable(false);
        txtEID.setEditable(false);
        txtEmailP.setEditable(false);
        txtSpeciality.setEditable(false);
        txtUNameP.setEditable(false);
        txtPassP.setEditable(false);

    }//GEN-LAST:event_btnSavePDActionPerformed

    private void btnUpdatePDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePDActionPerformed
        // TODO add your handling code here:
        btnSavePD.setEnabled(true);
        txtName.setEditable(true);
        txtEID.setEditable(true);
        txtEmailP.setEditable(true);
        txtSpeciality.setEditable(true);
        txtUNameP.setEditable(true);
        txtPassP.setEditable(true);

        btnUpdatePD.setEnabled(false);

    }//GEN-LAST:event_btnUpdatePDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackPD;
    private javax.swing.JButton btnSavePD;
    private javax.swing.JButton btnUpdatePD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtEID;
    private javax.swing.JTextField txtEmailP;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassP;
    private javax.swing.JTextField txtSpeciality;
    private javax.swing.JTextField txtUNameP;
    // End of variables declaration//GEN-END:variables
}
