/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.BusinessClass;
import UI.AdminstrativeRole.AdminWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author goutam
 */
public class adminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form adminJPanel
     */
    private JPanel userProcessContainer;
    private BusinessClass business;
    
    adminJPanel(JPanel userProcessContainer, BusinessClass business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPersonUser = new javax.swing.JLabel();
        adminDataPerson = new javax.swing.JLabel();
        adminPersonTitle = new javax.swing.JLabel();
        adminS1 = new javax.swing.JTextField();
        adminLoginButton = new javax.swing.JButton();
        adminS2 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 255, 204));

        adminPersonUser.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminPersonUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adminPersonUser.setText("Username :");

        adminDataPerson.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminDataPerson.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adminDataPerson.setText("Password :");

        adminPersonTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        adminPersonTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPersonTitle.setText("Welcome");

        adminS1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        adminLoginButton.setBackground(new java.awt.Color(255, 204, 204));
        adminLoginButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adminLoginButton.setText("login");
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });

        adminS2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPersonTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminPersonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDataPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(adminLoginButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminS2)
                            .addComponent(adminS1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPersonTitle)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPersonUser)
                    .addComponent(adminS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDataPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(adminLoginButton)
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        // TODO add your handling code here:
       String username = adminS1.getText();
String password = adminS2.getText();

if ((username.equals("admin") && password.equals("Pass")) ||
    (username.equals("admin2") && password.equals("admin2Pass")) ||
    (username.equals("admin3") && password.equals("admin3Pass"))) {
    JOptionPane.showMessageDialog(this, "Login success.");
    AdminWorkAreaJPanel awajp = new AdminWorkAreaJPanel(userProcessContainer, business);
    userProcessContainer.add("AdminWorkAreaJPanel",awajp);
    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
    layout.next(userProcessContainer);
}
else {
    JOptionPane.showMessageDialog(this, "Login failed. Please check your credentials.");
}

        
    }//GEN-LAST:event_adminLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminDataPerson;
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JLabel adminPersonTitle;
    private javax.swing.JLabel adminPersonUser;
    private javax.swing.JTextField adminS1;
    private javax.swing.JPasswordField adminS2;
    // End of variables declaration//GEN-END:variables
}
