/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Driver;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


public class DriverJPanel extends javax.swing.JPanel {

    
    Driver driver;
    public DriverJPanel(Driver driver) {
        initComponents();
        this.driver=driver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDrivingLicense = new javax.swing.JLabel();
        lblDLNO = new javax.swing.JLabel();
        LBLDOI = new javax.swing.JLabel();
        lblValidTill = new javax.swing.JLabel();
        txtDrivingLicense = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtDOI = new com.toedter.calendar.JDateChooser();
        txtValidity = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(613, 588));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDrivingLicense.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblDrivingLicense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrivingLicense.setText("Driving License");
        add(lblDrivingLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 570, 51));

        lblDLNO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDLNO.setText("DLNO:");
        add(lblDLNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 118, 31));

        LBLDOI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LBLDOI.setText("Date Of Issue:");
        add(LBLDOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 160, 31));

        lblValidTill.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblValidTill.setText("Validity:");
        add(lblValidTill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 118, 31));
        add(txtDrivingLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 130, -1));

        btnSave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 110, 40));
        add(txtDOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 130, 30));
        add(txtValidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/cardrive.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 620, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(txtDOI.getDate());
        driver.setDOI(date);
        driver.setDLNO(txtDrivingLicense.getText());
        SimpleDateFormat sdf1=new SimpleDateFormat("yyyy-MM-dd");
        String date1=sdf1.format(txtValidity.getDate());
        driver.setValidtill(date);
         JOptionPane.showMessageDialog(this,"The Information Is Saved");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLDOI;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDLNO;
    private javax.swing.JLabel lblDrivingLicense;
    private javax.swing.JLabel lblValidTill;
    private com.toedter.calendar.JDateChooser txtDOI;
    private javax.swing.JTextField txtDrivingLicense;
    private com.toedter.calendar.JDateChooser txtValidity;
    // End of variables declaration//GEN-END:variables
}
