/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaswanth
 */
public class PersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonJPanel
     */
    Person person;
    public PersonJPanel(Person person) {
        initComponents();
        this.person=person;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PersonDetails = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        txtWebsite = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtFullName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(613, 588));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PersonDetails.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        PersonDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonDetails.setText("Person Details");
        jPanel1.add(PersonDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 770, 29));

        lblFullName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFullName.setText("FullName:");
        jPanel1.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 110, -1));

        lblAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAddress.setText("Date Of Birth:");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, -1));

        lblBloodGroup.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblBloodGroup.setText("BloodGroup:");
        jPanel1.add(lblBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, -1));

        lblEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEmail.setText("Email:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 86, -1));

        lblSSN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSSN.setText("SSN:");
        jPanel1.add(lblSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 86, -1));

        lblDOB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDOB.setText("Address:");
        jPanel1.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 86, -1));

        lblAge.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAge.setText("Age:");
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 86, -1));

        lblContactNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblContactNumber.setText("ContactNumber:");
        jPanel1.add(lblContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        lblURL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblURL.setText("URL:");
        jPanel1.add(lblURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 86, -1));

        lblWebsite.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblWebsite.setText("Website:");
        jPanel1.add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 86, -1));
        jPanel1.add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 330, 30));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 330, -1));
        jPanel1.add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 330, -1));
        jPanel1.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 330, 30));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 330, -1));
        jPanel1.add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 330, -1));
        jPanel1.add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 330, -1));
        jPanel1.add(txtWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 330, -1));

        btnSave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 111, -1));
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 330, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 330, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/man-drawing-11551056782z3myk3vcnm.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        person.setFullName(txtFullName.getText());
        person.setAge(txtAge.getText());
        person.setBloodGroup(txtBloodGroup.getText());
        person.setContactNumber(txtContactNumber.getText());
        person.setDOB(txtDOB.getText());
        person.setUrl(txtURL.getText());
        person.setWebsite(txtWebsite.getText());
        person.setEmail(txtEmail.getText());
        person.setAddress(txtAddress.getText());
        person.setSsn(txtSSN.getText());

        JOptionPane.showMessageDialog(this,"The Information Is Saved");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PersonDetails;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblURL;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables

  
}
