/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Doctor;
import Model.Driver;
import Model.InsuranceCoverage;
import Model.Person;
import Model.VehicleRegistration;
import Model.patient;


/**
 *
 * @author Jaswanth
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    Doctor doctor;
    InsuranceCoverage Insurancecoverage;
    Driver driver;
    VehicleRegistration vehicleregistration;
    patient Patient;
    String reportText;
    public ViewJPanel(Person person,Doctor doctor,InsuranceCoverage Insurancecoverage,Driver driver,
                      VehicleRegistration vehicleregistration,patient Patient) {
        initComponents();
        this.person=person;
        this.doctor=doctor;
        this.Insurancecoverage=Insurancecoverage;
        this.Patient=Patient;
        this.vehicleregistration=vehicleregistration;
        this.driver=driver;
        displayPerson();
        displayDoctor();
        displayInsurancecoverage();
        displayPatient();
        displayvehicleregistration();
        displaydriver();
        reportText = generateReportText(person,doctor,Insurancecoverage,driver,vehicleregistration,Patient);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtBloodGroup = new javax.swing.JTextField();
        lblContactNumber = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        txtWebsite = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtId = new javax.swing.JTextField();
        lblAllergies = new javax.swing.JLabel();
        txtDoctor = new javax.swing.JTextField();
        lblInsuranceCoverage = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        lblDOLV = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        lblDOA = new javax.swing.JLabel();
        txtAllergies = new javax.swing.JTextField();
        txtInsuranceCoverage = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        lblMode = new javax.swing.JLabel();
        lblDOR = new javax.swing.JLabel();
        lblDOI = new javax.swing.JLabel();
        txtMode = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtDOR = new javax.swing.JTextField();
        txtDOI = new javax.swing.JTextField();
        lblPremium = new javax.swing.JLabel();
        lblCoorporateId = new javax.swing.JLabel();
        lblDAmount = new javax.swing.JLabel();
        lblBenifits = new javax.swing.JLabel();
        lblAmountToPay = new javax.swing.JLabel();
        txtAmountToPay = new javax.swing.JTextField();
        txtBenifits = new javax.swing.JTextField();
        txtPremium = new javax.swing.JTextField();
        txtCoorporateId = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress1 = new javax.swing.JTextArea();
        txtDAmount = new javax.swing.JTextField();
        txtDEmail = new javax.swing.JTextField();
        txtQualification = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtSpeciality = new javax.swing.JTextField();
        txtDFullName = new javax.swing.JTextField();
        lblQualification = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblDoctorId = new javax.swing.JLabel();
        lblDFullName = new javax.swing.JLabel();
        lblDEmail = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDAddress = new javax.swing.JTextArea();
        lblDAddress = new javax.swing.JLabel();
        lblSpeciality = new javax.swing.JLabel();
        txtDoctorId = new javax.swing.JTextField();
        lblDLNO = new javax.swing.JLabel();
        LBLDOI = new javax.swing.JLabel();
        lblValidTill = new javax.swing.JLabel();
        txtDLNO = new javax.swing.JTextField();
        txtDOI1 = new javax.swing.JTextField();
        txtValidity = new javax.swing.JTextField();
        txtDOLV = new javax.swing.JTextField();
        txtDONA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/1385507 (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PATIENT REPORT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1129, 32));

        lblWebsite.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblWebsite.setText("Website:");
        jPanel1.add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 97, 44));

        lblFullName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFullName.setText("FullName:");
        jPanel1.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 102, 44));

        lblAge.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAge.setText("Age:");
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 280, 97, 44));

        lblURL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblURL.setText("URL:");
        jPanel1.add(lblURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 110, 44));

        lblDOB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDOB.setText("Address:");
        jPanel1.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 248, 99, 44));

        lblAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAddress.setText("Date Of Birth:");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 113, 133, 44));

        lblSSN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSSN.setText("SSN:");
        jPanel1.add(lblSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 226, 65, 44));

        lblBloodGroup.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblBloodGroup.setText("BloodGroup:");
        jPanel1.add(lblBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 105, 125, 44));

        lblEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEmail.setText("Email:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 176, 77, 44));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 175, 433, -1));
        jPanel1.add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 238, 160, -1));

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        jPanel1.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 104, 160, 35));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 281, 93, 44));
        jPanel1.add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 106, 160, 44));

        lblContactNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblContactNumber.setText("ContactNumber:");
        jPanel1.add(lblContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 176, 168, 44));
        jPanel1.add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 175, 189, 35));
        jPanel1.add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 390, 342, 30));
        jPanel1.add(txtWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 391, 390, 30));
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 112, 160, 33));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 214, 387, 150));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 503, 166, -1));

        lblAllergies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAllergies.setText("Allergies:");
        jPanel1.add(lblAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 543, 137, -1));

        txtDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(txtDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 503, 211, -1));

        lblInsuranceCoverage.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblInsuranceCoverage.setText("Insurance Coverage:");
        jPanel1.add(lblInsuranceCoverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 543, 190, -1));

        lblDoctor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDoctor.setText("Doctor:");
        jPanel1.add(lblDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 502, 101, -1));

        lblDOLV.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDOLV.setText("Date Of Last Visit:");
        jPanel1.add(lblDOLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 502, 190, -1));

        lblPatientId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPatientId.setText("Patient Id:");
        jPanel1.add(lblPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 502, 190, -1));

        lblDOA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDOA.setText("Date Of Next Arrival:");
        jPanel1.add(lblDOA, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 543, 190, -1));
        jPanel1.add(txtAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 544, 116, -1));
        jPanel1.add(txtInsuranceCoverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 544, 222, -1));

        lblSerialNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSerialNumber.setText("Serial Number");
        jPanel1.add(lblSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 855, 143, 27));

        lblMode.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMode.setText("Model:");
        jPanel1.add(lblMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 861, 99, 27));

        lblDOR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDOR.setText("DOR");
        jPanel1.add(lblDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 852, 61, 27));

        lblDOI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDOI.setText("DOI");
        jPanel1.add(lblDOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 855, 45, 27));

        txtMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeActionPerformed(evt);
            }
        });
        jPanel1.add(txtMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 864, 175, -1));
        jPanel1.add(txtSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 858, 175, -1));
        jPanel1.add(txtDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 854, 175, -1));
        jPanel1.add(txtDOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 858, 175, -1));

        lblPremium.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPremium.setText("Premium:");
        jPanel1.add(lblPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 1041, 107, 24));

        lblCoorporateId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCoorporateId.setText("Coorporate Id:");
        jPanel1.add(lblCoorporateId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1041, -1, 24));

        lblDAmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDAmount.setText("Deductable Amount:");
        jPanel1.add(lblDAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1231, 180, 24));

        lblBenifits.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblBenifits.setText("Benifits:");
        jPanel1.add(lblBenifits, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 1135, 112, 24));

        lblAmountToPay.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAmountToPay.setText("Amount To Pay:");
        jPanel1.add(lblAmountToPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 1231, 158, 24));
        jPanel1.add(txtAmountToPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 1233, 290, -1));

        txtBenifits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenifitsActionPerformed(evt);
            }
        });
        jPanel1.add(txtBenifits, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 1099, 305, 99));
        jPanel1.add(txtPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 1043, 152, -1));
        jPanel1.add(txtCoorporateId, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 1043, 155, -1));

        txtAddress1.setColumns(20);
        txtAddress1.setRows(5);
        jScrollPane3.setViewportView(txtAddress1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 1112, 474, -1));
        jPanel1.add(txtDAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 1233, 253, -1));
        jPanel1.add(txtDEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 773, 346, -1));
        jPanel1.add(txtQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 773, 189, -1));
        jPanel1.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 707, 209, -1));
        jPanel1.add(txtSpeciality, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 624, 149, -1));
        jPanel1.add(txtDFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 635, 204, -1));

        lblQualification.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblQualification.setText("Qualification");
        jPanel1.add(lblQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 772, -1, -1));

        lblMobile.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMobile.setText("Mobile:");
        jPanel1.add(lblMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 706, -1, -1));

        lblDoctorId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDoctorId.setText("DoctorId:");
        jPanel1.add(lblDoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 623, 96, -1));

        lblDFullName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDFullName.setText("FullName:");
        jPanel1.add(lblDFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 637, -1, -1));

        lblDEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDEmail.setText("Email:");
        jPanel1.add(lblDEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 772, 94, -1));

        txtDAddress.setColumns(20);
        txtDAddress.setRows(5);
        jScrollPane4.setViewportView(txtDAddress);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 675, 436, -1));

        lblDAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDAddress.setText("Address:");
        jPanel1.add(lblDAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 709, -1, -1));

        lblSpeciality.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSpeciality.setText("Speciality:");
        jPanel1.add(lblSpeciality, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 623, 112, -1));
        jPanel1.add(txtDoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 624, 132, -1));

        lblDLNO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDLNO.setText("DLNO:");
        jPanel1.add(lblDLNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 953, 150, 31));

        LBLDOI.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LBLDOI.setText("Date Of Issue:");
        jPanel1.add(LBLDOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 960, 164, -1));

        lblValidTill.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblValidTill.setText("Validity:");
        jPanel1.add(lblValidTill, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 957, 112, -1));
        jPanel1.add(txtDLNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 958, 130, -1));
        jPanel1.add(txtDOI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 958, 159, -1));
        jPanel1.add(txtValidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 958, 163, -1));
        jPanel1.add(txtDOLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1019, 503, 125, -1));
        jPanel1.add(txtDONA, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 544, 185, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("PERSON DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 1583, 44));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 444, 1180, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("PATIENT DETAILS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 459, 220, 37));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 572, 1180, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("DOCTOR DETAILS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 572, 194, 39));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 811, 1190, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Vehicle Registration");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 823, 234, 32));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 901, 1190, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Driver Details:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 916, 230, 31));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 990, 1190, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("Insurance Coverage");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 999, 185, 30));

        lblAddress1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAddress1.setText("Address");
        jPanel1.add(lblAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1139, 79, 24));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/1385507 (1).jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 1280));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorActionPerformed

    private void txtModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeActionPerformed

    private void txtBenifitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenifitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenifitsActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLDOI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblAmountToPay;
    private javax.swing.JLabel lblBenifits;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCoorporateId;
    private javax.swing.JLabel lblDAddress;
    private javax.swing.JLabel lblDAmount;
    private javax.swing.JLabel lblDEmail;
    private javax.swing.JLabel lblDFullName;
    private javax.swing.JLabel lblDLNO;
    private javax.swing.JLabel lblDOA;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOI;
    private javax.swing.JLabel lblDOLV;
    private javax.swing.JLabel lblDOR;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblDoctorId;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblInsuranceCoverage;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblQualification;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JLabel lblURL;
    private javax.swing.JLabel lblValidTill;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextArea txtAddress1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergies;
    private javax.swing.JTextField txtAmountToPay;
    private javax.swing.JTextField txtBenifits;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtCoorporateId;
    private javax.swing.JTextArea txtDAddress;
    private javax.swing.JTextField txtDAmount;
    private javax.swing.JTextField txtDEmail;
    private javax.swing.JTextField txtDFullName;
    private javax.swing.JTextField txtDLNO;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDOI;
    private javax.swing.JTextField txtDOI1;
    private javax.swing.JTextField txtDOLV;
    private javax.swing.JTextField txtDONA;
    private javax.swing.JTextField txtDOR;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JTextField txtDoctorId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInsuranceCoverage;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtMode;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtSpeciality;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtValidity;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
      txtAddress.setText(person.getAddress());
      txtAge.setText(person.getAge());
      txtBloodGroup.setText(person.getBloodGroup());
      txtContactNumber.setText(person.getContactNumber());
      txtDOB.setText(person.getDOB());
      txtURL.setText(person.getUrl());
      txtWebsite.setText(person.getWebsite());
      txtEmail.setText(person.getEmail());
      txtFullName.setText(person.getFullName());
      txtSSN.setText(person.getSsn());
      
     
    }

    private void displayDoctor() {
        txtDFullName.setText(doctor.getDFullName());
        txtDEmail.setText(doctor.getDoctorEmail());
        txtDoctorId.setText(doctor.getDoctorId());
        txtDAddress.setText(doctor.getOfficeAddress());
        txtSpeciality.setText(doctor.getSpeciality());
        txtQualification.setText(doctor.getQualification());
        txtMobile.setText(doctor.getDoctorMobile());
    }

    private void displayInsurancecoverage() {
        txtCoorporateId.setText(Insurancecoverage.getCorporateId());
        txtPremium.setText(Insurancecoverage.getPremium());
        txtAmountToPay.setText(Insurancecoverage.getAmountToPay());
        txtBenifits.setText(Insurancecoverage.getBenifits());
        txtAddress1.setText(Insurancecoverage.getAddress());
        txtDAmount.setText(Insurancecoverage.getDeductable());
                
        
     
    }

    private void displayPatient() {
        txtId.setText(Patient.getPatientID());
        txtDoctor.setText(Patient.getPrimaryDoctor());
        txtDONA.setText(Patient.getDONA());
        txtDOLV.setText(Patient.getDOLV());
        txtInsuranceCoverage.setText(Patient.getInsuranceCoverage());
        txtAllergies.setText(Patient.getAllergies());
        
    }

    private void displayvehicleregistration() {
        txtMode.setText(vehicleregistration.getModel());
        txtSerialNumber.setText(vehicleregistration.getSerialNo());
        txtDOR.setText(vehicleregistration.getDOR());
        txtDOI.setText(vehicleregistration.getDOI());
        
    }

    private void displaydriver() {
        txtDLNO.setText(driver.getDLNO());
        txtDOI1.setText(driver.getDOI());
        txtValidity.setText(driver.getValidtill());
    }
      public static String generateReportText(Person person,Doctor doctor,InsuranceCoverage Insurancecoverage,Driver driver,
            VehicleRegistration vehicleregistration,patient Patient) {
        // Generate the report text here
        String report = "Report:\n";
        
        report += "-------------PersonDetails--------------------------\n";
     
      
        report += "Name: " + person.getAddress() + "\n";
        report += "Age: " + person.getAge() + "\n";
        report += "BloodGroup: " + person.getBloodGroup() + "\n";
        report += "Mobile: " + person.getContactNumber() + "\n";
        report += "DOB: " + person.getDOB() + "\n";
        report += "Url: " + person.getUrl() + "\n";
        report += "Website: " + person.getWebsite() + "\n";
        report += "Email: " + person.getEmail() + "\n";
       
       
        report += "-------------DriverDetails--------------------------\n";
        report += "DLNO: " +driver.getDLNO() + "\n";
        report += "DOI1: " +driver.getDOI()  + "\n";
        report += "Validity: " + driver.getValidtill() + "\n";
        
     
        report += "-------------VehicleregistrationDetails--------------------------\n";
        report += "Model: " + vehicleregistration.getModel() + "\n";
        report += "SerialNo: " + vehicleregistration.getSerialNo() + "\n";
        report += "DOR: " + vehicleregistration.getDOR() + "\n" ;
        report += "DOI: " + vehicleregistration.getDOI() + "\n";
        
        report += "-------------Ptient Details--------------------------\n";
        report += "PatientID: " + Patient.getPatientID()+ "\n";
        report += "PrimaryDoctor: " +  Patient.getPrimaryDoctor() + "\n";
        report += "DONA: " + Patient.getDONA() + "\n";
        report += "DOLV: " +  Patient.getDOLV() + "\n";
        report += "InsuranceCoverage: " + Patient.getInsuranceCoverage() + "\n";
        report += "Allergies: " +Patient.getAllergies() + "\n";
        
     
        report += "-------------Doctor Details--------------------------\n";
        report += "FullName: " +doctor.getDFullName()+ "\n";
        report += "Email: " + doctor.getDoctorEmail()+ "\n" ;
        report += "ID: " + doctor.getDoctorId()+ "\n";
        report += "OfficeAddress: " + doctor.getOfficeAddress() + "\n";
        report += "Speciality: " + doctor.getSpeciality() + "\n";
        report += "Qualification: " + doctor.getQualification() + "\n";
        report += "Mobile: " + doctor.getDoctorMobile() + "\n";
         
        
        
        report += "-------------Insurance Details--------------------------\n";
        report += "CorporateId: " + Insurancecoverage.getCorporateId() + "\n";
        report += "Premium: " + Insurancecoverage.getPremium()+ "\n";
        report += "AmountToPay: " + Insurancecoverage.getAmountToPay()+ "\n" ;
        report += "Benifits: " + Insurancecoverage.getBenifits() + "\n";
        report += "Address: " + Insurancecoverage.getAddress() + "\n";
        report += "Deducted Amount: " + Insurancecoverage.getDeductable() + "\n";
        return report;
      }
}
