/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Doctor;

import Model.Account;
import Model.DoctorPrescription;
import Model.EcoSystem;
import Model.EnterPrise;
import Model.MedicalEquipStoreEnterPrise;
import Model.Network;
import Model.Organization.Organization;
import Model.Organization.DoctorOrganization;
import Model.Organization.EquipmentHandlingOrganization;
import Model.PrescriptionRepo;
import Model.WorkQueue.Doctor_WorkRequest;
import Model.WorkQueue.HealthCareEquipment_WorkRequest;
import Model.WorkQueue.Work_Request;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaswa
 */
public class HealthCareEquipmentManagementJpanel extends javax.swing.JPanel {

    private DoctorPrescription doc_pres;
    private Doctor_WorkRequest doc_req;
    private EnterPrise enter;
    private Account acc;
    private JPanel upperContainer;
    private DoctorOrganization doctor_Org;
    private PrescriptionRepo p_repo;
    private EcoSystem eco;
    private Network ntwk;
    private EnterPrise.EntType enttype;
    private EquipmentHandlingOrganization eqhandle;
    private MedicalEquipStoreEnterPrise medenter;

    /**
     * Creates new form HealthCareEquipmentManagementJpanel
     */
    public HealthCareEquipmentManagementJpanel(JPanel upperContainer, Account acc, DoctorOrganization doctor_Org, EnterPrise enter, EcoSystem eco, Network ntwk) {
        initComponents();
        this.upperContainer = upperContainer;
        this.acc = acc;
        this.enter = enter;
        this.doctor_Org = doctor_Org;
        this.ntwk = ntwk;
        this.eco = eco;

        populateWorkTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelscroll1 = new javax.swing.JScrollPane();
        tblMedEq = new javax.swing.JTable();
        labelurglevel = new javax.swing.JLabel();
        comburgency = new javax.swing.JComboBox();
        labelquantity = new javax.swing.JLabel();
        textfieldquantity = new javax.swing.JSpinner();
        buttonback = new javax.swing.JButton();
        buttonrequest = new javax.swing.JButton();
        labelheader = new javax.swing.JLabel();
        labelmeqequip = new javax.swing.JLabel();
        comequip = new javax.swing.JComboBox();
        buttonrefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        tblMedEq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICAL EQUIPMENT", "MESSAGE", "QUANTITY", "SENDER", "RECEIVER", "STATUS", "REQUEST DATE", "ACTUAL PRICE", "LOAN PRICE"
            }
        ));
        panelscroll1.setViewportView(tblMedEq);

        labelurglevel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelurglevel.setForeground(new java.awt.Color(153, 255, 255));
        labelurglevel.setText("URGENCY LEVEL:");

        comburgency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Please select--", "VERY CRITICAL(<2 HRS)", "MODERATE(<5 HRS)", "LOW PRIORITY(24 HRS)" }));
        comburgency.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comburgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comburgencyActionPerformed(evt);
            }
        });

        labelquantity.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelquantity.setForeground(new java.awt.Color(153, 255, 255));
        labelquantity.setText("QUANTITY:");

        textfieldquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonback.setBackground(new java.awt.Color(204, 204, 204));
        buttonback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonback.setText("<<Back");
        buttonback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });

        buttonrequest.setBackground(new java.awt.Color(153, 153, 153));
        buttonrequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/service request.png"))); // NOI18N
        buttonrequest.setText("Request");
        buttonrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrequestActionPerformed(evt);
            }
        });

        labelheader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelheader.setForeground(new java.awt.Color(153, 255, 255));
        labelheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelheader.setText("REQUEST MEDICAL EQUIPMENT");

        labelmeqequip.setBackground(new java.awt.Color(204, 204, 204));
        labelmeqequip.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelmeqequip.setForeground(new java.awt.Color(153, 255, 255));
        labelmeqequip.setText("MEDICAL EQUIPMENT:");

        comequip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Please Select--", "Oxygen Cylinder", "Pulse Oxymeter", "Stretcher", "Thermometer", "Stethescope", "Diabetes Machine", "COVID Testing Kits", "Syringes", "Blood pressure Kit", " " }));
        comequip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comequip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comequipActionPerformed(evt);
            }
        });

        buttonrefresh.setBackground(new java.awt.Color(204, 204, 204));
        buttonrefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonrefresh.setText("Refresh");
        buttonrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrefreshActionPerformed(evt);
            }
        });

        jButton1.setText("REMOVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelheader, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(buttonrefresh)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelmeqequip, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelurglevel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comburgency, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comequip, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addComponent(labelquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelheader, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(panelscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelmeqequip, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfieldquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comequip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelurglevel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comburgency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addComponent(buttonback))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comburgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comburgencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comburgencyActionPerformed

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        upperContainer.remove(this);
        CardLayout layout = (CardLayout) upperContainer.getLayout();
        layout.previous(upperContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonbackActionPerformed

    private void buttonrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonrequestActionPerformed
        HealthCareEquipment_WorkRequest request = new HealthCareEquipment_WorkRequest();

try {
    // Set request details
    request.setEquipName(comequip.getSelectedItem().toString());
    request.setSender(acc);
    request.setStatus("Sent");
    request.setUrgencyLevel(comburgency.getSelectedItem().toString());

    // Parse quantity as an integer
    try {
        request.setQuantity(Integer.parseInt(textfieldquantity.getValue().toString()));
    } catch (NumberFormatException e) {
        throw new IllegalArgumentException("Please enter a valid quantity.");
    }

    // Set other request details
    Date date = new Date();
    int min = 20;
    int max = 40;
    Random rand = new Random();
    int n1 = rand.nextInt((max - min)) + 1;
    int n2 = rand.nextInt(10) + 1;
    request.setActualprice(n1);
    request.setHospitalName(enter.getOrgName());
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    request.setRequestDate(dateFormat.format(date));
    request.setLoanprice(n2);

    Organization org = null;

    // Find the DoctorOrganization in the current enterprise
    for (Organization organization : enter.getOrgaDirectory().getOrganizations()) {
        if (organization instanceof DoctorOrganization) {
            org = organization;
            break;
        }
    }

    if (org != null) {
        // Add the request to the DoctorOrganization's work queue
        org.getWQ().getWorkRequestList().add(request);
        // Also add the request to the account's work queue
        acc.getWorkQ().getWorkRequestList().add(request);
    }

    // Iterate through networks and enterprises to find Equipment Organization
    for (Network network : eco.getNetworks()) {
        if (ntwk.getNetwork_name().equals(this.ntwk.getNetwork_name())) {
            for (EnterPrise ent : ntwk.getEnterpriseRepo().getEnterpRepo()) {
                for (Organization organization : ent.getOrgaDirectory().getOrganizations()) {
                    if (organization.getOrgName().equals("Equipment Organization")) {
                        organization.getWQ().getWorkRequestList().add(request);
                    }
                }
            }
        }
    }

    // Add the request to the account's work queue again
    acc.getWorkQ().getWorkRequestList().add(request);
    // Update the UI
    populateWorkTable();
     } catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     } catch (Exception e) {
    JOptionPane.showMessageDialog(null, "An unexpected error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace(); // Print the stack trace for debugging purposes
}
             
    }//GEN-LAST:event_buttonrequestActionPerformed

    private void comequipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comequipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comequipActionPerformed

    private void buttonrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonrefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonrefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblMedEq.getSelectedRow();

    // Check if a row is selected
    if (selectedRowIndex >= 0) {
        // Remove the selected row from the table's model
        DefaultTableModel model = (DefaultTableModel) tblMedEq.getModel();
        model.removeRow(selectedRowIndex);
    } else {
        // If no row is selected, show a message to the user
        JOptionPane.showMessageDialog(null, "Please select a row to remove.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateWorkTable() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        DefaultTableModel model = (DefaultTableModel) tblMedEq.getModel();

        model.setRowCount(0);
        for (Work_Request request : doctor_Org.getWQ().getWorkRequestList()) {
            Object[] row = new Object[9];
            
             row[0] = ((HealthCareEquipment_WorkRequest) request);
            String urgencyLevel = ((HealthCareEquipment_WorkRequest) request).getUrgencyLevel();
            row[1] = urgencyLevel;
            int quantity = ((HealthCareEquipment_WorkRequest) request).getQuantity();
            row[2] = quantity;
            row[3] = request.getSender();
            row[4] = ((HealthCareEquipment_WorkRequest) request).getReceiver();
            row[5] = request.getStatus();

            String expectedArrivalTime = ((HealthCareEquipment_WorkRequest) request).getExpectedArrivalTime();

            row[6] = request.getRequestDate();
            row[7] = ((HealthCareEquipment_WorkRequest) request).getActualprice();
            row[8] = ((HealthCareEquipment_WorkRequest) request).getLoanprice();

            model.addRow(row);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonrefresh;
    private javax.swing.JButton buttonrequest;
    private javax.swing.JComboBox comburgency;
    private javax.swing.JComboBox comequip;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelheader;
    private javax.swing.JLabel labelmeqequip;
    private javax.swing.JLabel labelquantity;
    private javax.swing.JLabel labelurglevel;
    private javax.swing.JScrollPane panelscroll1;
    private javax.swing.JTable tblMedEq;
    private javax.swing.JSpinner textfieldquantity;
    // End of variables declaration//GEN-END:variables

}
